name: Push to registry on release

on:
    release:
        types: [published]

jobs:
    push_to_registry_unix:
        name: Push Docker unix image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Push to Docker Hub
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: getmargin/docker-redis-cluster
                tag_with_ref: true
    push_to_registry_osx:
        name: Push Docker osx image to Docker Hub
        runs-on: macos-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Push to Docker Hub
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: getmargin/docker-redis-cluster
                tag_with_ref: true